Rebase Omadeb onto Omakube

diff --git a/bin/omakub-tui-install b/bin/omakub-tui-install
--- a/bin/omakub-tui-install
+++ b/bin/omakub-tui-install
@@ -1,16 +1,16 @@
 #!/bin/bash
 
-if [ "$#" -ne 4 ]; then
+set -e
+
+if [ "$#" -ne 3 ]; then
   echo -e "\e[32mLet's create a TUI shortcut you can start with the app launcher.\n\e[0m"
   APP_NAME=$(gum input --prompt "Name> " --placeholder "My TUI")
   APP_EXEC=$(gum input --prompt "Launch Command> " --placeholder "lazydocker or bash -c 'dust; read -n 1 -s'")
-  WINDOW_STYLE=$(gum choose --header "Window style" float tile)
-  ICON_URL=$(gum input --prompt "Icon URL> " --placeholder "See https://dashboardicons.com (must use PNG!)")
+  ICON_URL=$(gum input --prompt "Icon URL> " --placeholder "See https://dashboardicons.com (must use PNG or SVG!)")
 else
   APP_NAME="$1"
   APP_EXEC="$2"
-  WINDOW_STYLE="$3"
-  ICON_URL="$4"
+  ICON_URL="$3"
 fi
 
 if [[ -z "$APP_NAME" || -z "$APP_EXEC" || -z "$ICON_URL" ]]; then
@@ -20,27 +20,25 @@ fi
 
 ICON_DIR="$HOME/.local/share/applications/icons"
 DESKTOP_FILE="$HOME/.local/share/applications/$APP_NAME.desktop"
-ICON_PATH="$ICON_DIR/$APP_NAME.png"
 
-mkdir -p "$ICON_DIR"
-
-if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
-  echo "Error: Failed to download icon."
-  return 1
-fi
-
-if [[ $WINDOW_STYLE == "float" ]]; then
-  APP_CLASS="TUI.float"
+if [[ ! "$ICON_URL" =~ ^https?:// ]] && [ -f "$ICON_URL" ]; then
+  ICON_PATH="$ICON_URL"
 else
-  APP_CLASS="TUI.tile"
+  ICON_PATH="$ICON_DIR/$APP_NAME.png"
+  mkdir -p "$ICON_DIR"
+  if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
+    echo "Error: Failed to download icon."
+    exit 1
+  fi
 fi
+
 
 cat >"$DESKTOP_FILE" <<EOF
 [Desktop Entry]
 Version=1.0
 Name=$APP_NAME
 Comment=$APP_NAME
-Exec=alacritty --class $APP_CLASS -e $APP_EXEC
+Exec=xdg-terminal-exec $APP_EXEC
 Terminal=false
 Type=Application
 Icon=$ICON_PATH
diff --git a/bin/omakub-update b/bin/omakub-update
--- a/bin/omakub-update
+++ b/bin/omakub-update
@@ -2,7 +2,9 @@
 
 set -e
 
-omakub-update-git
-omakub-migrate
-omakub-update-system-pkgs
-omakub-update-restart
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\033[0m"' ERR
+
+if [[ $1 == "-y" ]] || omakub-update-confirm; then
+  omakub-update-git
+  omakub-update-perform
+fi
